#!/bin/bash

export HASHIAPPNAME="${hashiapp_name}"
export HASHIAPP_VERSION="${hashiapp_version}"
export HASHIAPP_ZIPFILE="$HASHIAPP"$HASHIAPP_VERSION"_linux_amd64.zip"
export HASHIAPP_DOWNLOAD_PATH="/tmp/"
export HASHIAPP_DOWNLOAD_URL="https://releases.hashicorp.com/$HASHIAPPNAME/"$HASHIAPP_VERSION"/$HASHIAPP"$HASHIAPP_VERSION"_linux_amd64.zip"

export HASHIAPP_USER="$HASHIAPPNAME"
export HASHIAPP_GROUP="$HASHIAPPNAME"

export HASHIAPP_BASE_PATH="/opt/$HASHIAPPNAME"
export HASHIAPP_BIN_PATH=$HASHIAPP_BASE_PATH"/bin"
export HASHIAPP_CONFIG_PATH=$HASHIAPP_BASE_PATH"/config"
export HASHIAPP_DATA_PATH=$HASHIAPP_BASE_PATH"/data"

mkdir --parents $HASHIAPP_BIN_PATH
mkdir --parents $HASHIAPP_CONFIG_PATH
mkdir --parents $HASHIAPP_DATA_PATH

wget -P $HASHIAPP_DOWNLOAD_PATH $HASHIAPP_DOWNLOAD_URL

unzip -d $HASHIAPP_DOWNLOAD_PATH $HASHIAPP_DOWNLOAD_PATH$HASHIAPP_ZIPFILE

mv "$HASHIAPP_DOWNLOAD_PATH/$HASHIAPPNAME" $HASHIAPP_BIN_PATH

ln -s $HASHIAPP_BIN_PATH /usr/local/bin

useradd --system --home $HASHIAPP_CONFIG_PATH --shell /bin/false $HASHIAPP_USER

chown --recursive $HASHIAPP_USER:$HASHIAPP_GROUP $HASHIAPP_BASE_PATH
